DERM1M_CLASSNAMES=['acne', 'abscess', 'acanthosis nigricans', 'acquired autoimmune bullous diseaseherpes gestationis', 'acne keloidalis nuchae', 'acne urticata', 'acne vulgaris', 'acrokeratosis verruciformis', 'actinic granuloma', 'actinic solar damage(actinic keratosis)', 'actinic solar damage(cutis rhomboidalis nuchae)', 'actinic solar damage(pigmentation)', 'actinic solar damage(solar elastosis)', 'actinic solar damage(solar purpura)', 'actinic solar damage(telangiectasia)', 'acute and chronic dermatitis', 'acute constitutional eczema', 'acute dermatitis', 'acute dermatitis, nos', 'acute generalized exanthematous pustulosis', 'acute vesicular dermatitis', 'adnexal neoplasm', 'allergic contact dermatitis', 'alopecia areata', 'amyloidosis', 'animal bite - wound', 'annular erythema', 'angular cheilitis', 'angiofibroma', 'angiokeratoma', 'angioma', 'apocrine hydrocystoma', 'arsenical keratosis', 'atopic dermatitis', 'basal cell carcinoma', 'basal cell carcinoma morpheiform', "beau's lines", 'becker nevus', 'benign keratosis', 'blister', 'blue nevus', "bowen's disease", 'bullous disease', 'bullous pemphigoid', 'burn of forearm', 'burn of skin', 'café au lait macule', 'calcinosis cutis', 'callus', 'candida intertrigo', 'candidiasis', 'cheilitis', 'chilblain', 'chronic dermatitis, nos', 'clubbing of fingers', 'compound nevus', 'condyloma', 'condyloma acuminatum', 'confluent and reticulated papillomatosis', 'congenital nevus', 'contact dermatitis', 'contact dermatitis caused by rhus diversiloba', 'contact dermatitis, nos', 'contact purpura', "crowe's sign", 'cutaneous horn', 'cutaneous larva migrans', 'cutaneous lupus', 'cutaneous sarcoidosis', 'cutaneous t cell lymphoma', 'cyst', 'darier-white disease', 'deep fungal infection', 'dermatitis herpetiformis', 'dermatofibroma', 'dermatosis papulosa nigra', 'desquamation', 'diffuse xanthoma', 'digital fibroma', 'dilated pore of winer', 'disseminated actinic porokeratosis', 'drug eruption', 'dry skin eczema', 'dyshidrosiform eczema', 'dysplastic nevus', 'eczema', 'eczema herpeticum', 'ecthyma', 'ecthyma gangrenosum', 'elephantiasis nostras', 'epidermal nevus', 'epidermoid cyst', 'erosion of skin', 'eruptive odontogenic cyst', 'eruptive xanthoma', 'erythema ab igne', 'erythema annulare centrifugum', 'erythema craquele', 'erythema dyschromicum perstans', 'erythema gyratum repens', 'erythema migrans', 'erythema multiforme', 'erythema nodosum', 'exfoliative dermatitis', 'exfoliative erythroderma', 'factitial dermatitis', 'favre racouchot', 'fibroma molle', 'fixed drug eruption', 'follicular mucinosis', 'foot ulcer', 'foreign body reaction of the skin', 'fox-fordyce disease', 'freckle', 'fungal dermatitis', 'fungal dermatosis', 'furuncle', 'geographic tongue', 'granulation tissue', 'granuloma annulare', "grover's disease", 'guttate psoriasis', 'hailey hailey disease', 'halo nevus', 'hand eczema', 'hand foot and mouth disease', 'hematoma of skin', 'hemangioma', 'hemosiderin pigmentation of lower limb due to varicose veins of lower limb', 'hemosiderin pigmentation of skin due to venous insufficiency', 'herpes simplex virus', 'herpes zoster', 'hidradenitis suppurativa', 'histiocytosis of skin', 'hyperkeratosis palmaris et plantaris', 'hyperpigmentation', 'hypertrophic scar', 'hypertrichosis', 'hypersensitivity', 'ichthyosis', 'idiopathic guttate hypomelanosis', 'impetigo', 'infantile atopic dermatitis', 'infected eczema', 'inflammatory dermatosis', 'insect bite', 'intertrigo', 'inverse psoriasis', 'irritant contact dermatitis', 'irritated seborrheic keratosis (from "sk/isk")', 'juvenile xanthogranuloma', 'junction nevus', "kaposi's sarcoma of skin", 'keloid', 'keratoderma', 'keratoacanthoma', 'keratolysis exfoliativa of wende', 'keratosis', 'keratosis pilaris', 'kerion', 'knuckle pads', 'koilonychia', 'lentigo', 'lentigo maligna', 'lentigo maligna melanoma', 'leukocytoclastic vasculitis', 'leukonychia', 'lichen amyloidosis', 'lichen nitidus', 'lichen planus', 'lichen sclerosis et atrophicus', 'lichen simplex chronicus', 'lichen spinulosus', 'lichen striatus', 'lipoma', 'livedo reticularis', 'local infection of wound', 'localized cutaneous vasculitis', 'localized skin infection', 'lupus erythematosus', 'lyme disease', 'lymphangioma', 'lymphocytic infiltrate of jessner', 'majocchi granuloma', 'melanin pigmentation due to exogenous substance', 'melanocytic nevus', 'melasma', 'median nail dystrophy', 'metastatic carcinoma', 'miliaria', 'milia', 'molluscum contagiosum', 'morphea', 'mucinosis', 'mucosal melanotic macule', 'mucocele', 'mycosis fungoides', 'myxoid cyst', 'naevus comedonicus', 'nail dystrophy', 'nail psoriasis', 'necrobiosis lipoidica', 'nematode infection', 'neurodermatitis', 'neurofibroma', 'neurofibromatosis', 'nevus depigmentosus', 'nevus incipiens', 'nevus sebaceous of jadassohn', 'nevus spilus', 'neutrophilic dermatoses', 'nummular eczema', 'onycholysis', 'onychomycosis', 'onychoschizia', 'organoid nevus', 'ota nevus', 'paronychia', 'parapsoriasis', 'pediculosis lids', 'pemphigus vulgaris', 'phytophotodermatitis', 'pilar cyst', 'pincer nail deformity', 'pigmented progressive purpuric dermatosis', 'pigmented purpuric eruption', 'pityriasis alba', 'pityriasis lichenoides', 'pityriasis lichenoides chronica', 'pityriasis lichenoides et varioliformis acuta', 'pityriasis rosea', 'pityriasis rubra pilaris', 'pityrosporum folliculitis', 'poikiloderma', 'poisoning by nematocyst', 'port wine stain', 'porokeratosis', 'porokeratosis actinic', 'porokeratosis of mibelli', 'poroma', 'post-inflammatory hyperpigmentation', 'post-inflammatory hypopigmentation', 'pressure ulcer', 'prurigo', 'prurigo nodularis', 'prurigo pigmentosa', 'psoriasis', 'pseudofolliculitis barbae', 'pseudorhinophyma', 'pustular psoriasis', 'pyoderma', 'pyoderma gangrenosum', 'pyogenic granuloma', 'radiodermatitis', 'relapsing polychondritis', 'rheumatoid nodule', 'rhinophyma', 'riehl melanosis', 'rosacea', 'sarcoidosis', 'scabies', 'scalp psoriasis', 'scar', 'scleroderma', 'scleromyxedema', 'skin and soft tissue atypical mycobacterial infection', 'skin infection', 'skin lesion in drug addict', 'skin tag', 'solid cystic basal cell carcinoma', 'squamous cell carcinoma', 'staphylococcal scalded skin syndrome', 'stasis dermatitis', 'stasis edema', 'stasis ulcer', 'steatocystoma multiplex', 'steroid acne', 'steroid use abusemisuse dermatitis', 'striae', 'subungual hematoma', 'sunburn', 'seborrheic keratoses', 'melanoma', 'superficial spreading melanoma ssm', 'superficial wound of body region', 'sweet syndrome', 'syphilis', 'syringoma', 'telangiectasia macularis eruptiva perstans', 'tick bite', 'tinea', 'tinea corporis', 'tinea cruris', 'tinea faciale', 'tinea manus', 'tinea pedis', 'tinea versicolor', 'traumatic blister', 'traumatic ulcer', 'tuberous sclerosis', 'tungiasis', 'ulcer', 'unilateral laterothoracic exanthem', 'urticaria', 'urticaria pigmentosa', 'urticarial vasculitis', 'varicella', 'varicose veins of lower extremity', 'vasculitis', 'venous lake', 'verruca vulgaris', 'viral exanthem', 'vitiligo', 'wound/abrasion', 'xanthelasma', 'xerosis', 'moles', 'phototherapy', 'dariers disease', 'ehlers danlos syndrome', 'palmoplantar pustulosis', 'late onset acne', 'miescher’s cheilitis', 'chronic palmoplantar pustular psoriasis', 'kaposi sarcoma', 'cholestasis of pregnancy', 'campbell de morgan spots', 'neonatal and infantile acne', 'transient acantholytic dermatosis', 'merkel cell carcinoma', 'incobotulinumtoxin a', 'leg veins', 'xerotic eczema', 'skin cancer', 'pruritus ani', 'naevus fusco-caeruleus zygomaticus', 'dry skin', 'viral exanthems: roseola', 'porphyria', 'zits', 'pigmentation of pregnancy', 'recurrent jaundice or recurrent cholestasis of pregnancy', 'strawberry birthmarks', 'fonseca’s disease', 'juvenile plantar dermatosis', 'muzzle rash', 'behcets disease', 'post-inflammatory pigmentation', 'cutaneous b-cell lymphoma', 'xeroderma pigmentosum', 'papular dermatoses of pregnancy', 'polymorphic eruption of pregnancy', 'poikiloderma of civatte', 'keratosis pilaris rubra faciei', 'superficial gyrate erythema', 'atopic winter feet', 'langerhans cell histiocytosis', 'palpable migrating erythema', 'fixed eruptions', 'discoid eczema', 'polymorphous light eruption', 'prurigo of pregnancy', 'chronic actinic dermatitis', 'erythema elevatum diutinum', 'granuloma faciale', 'raynaud phenomenon', 'degos disease', 'parvovirus b19 infection', 'pseudo-glucagonoma syndrome', 'childhood bullous pemphigoid', 'pruritic urticarial papules and plaques of pregnancy', 'sebaceous hyperplasia', 'drug-induced pigmentary changes', 'chondrodermatitis nodularis helicis', 'erosive pustular dermatosis of the scalp', 'sixth disease', 'drug eruptions & reactions', 'medication-induced cutaneous pigmentation', 'central centrifugal cicatricial alopecia', 'dermatologic syndromes associated with pregnancy', 'red stretch marks', 'sweet’s syndrome', 'prurigo gravidarum', 'norweigian scabies', 'hormonal acne', 'flushing', 'sun spots', 'ageing skin', 'spider veins', 'alopecia mucinosa', 'sand-worm eruption', 'nevus', 'vascular', 'no definitive diagnosis', 'autoimmune dermatitis', 'dermatitis', 'stevens-johnson syndrome', 'systemic disease', 'nail disease', 'folliculitis', 'skin diseases caused by warts', 'cellulitis', 'alopecia', 'epidermolysis bullosa', 'cutaneous leishmaniasis', 'flat wart', 'allergic reaction']
HAM_CLASSNAMES= ( "actinic keratosis", "basal cell carcinoma", "benign keratosis", "dermatofibroma","melanoma","nevus", "vascular")
PAD_CLASSNAMES= ( "nevus",  "basal cell carcinoma","actinic keratosis", "seborrheic keratosis","squamous cell carcinoma","melanoma")
DERMNET_CLASSNAMES = ('light diseases and disorders of pigmentation', 'acne and rosacea photos', 'warts molluscum and other viral infections', 'seborrheic keratoses and other benign tumors', 'cellulitis impetigo and other bacterial infections', 'poison ivy photos and other contact dermatitis', 'vasculitis photos', 'urticaria hives', 'melanoma skin cancer nevi and moles', 'eczema photos', 'herpes hpv and other stds photos', 'scabies lyme disease and other infestations and bites', 'tinea ringworm candidiasis and other fungal infections', 'actinic keratosis basal cell carcinoma and other malignant lesions', 'atopic dermatitis photos', 'lupus and other connective tissue diseases', 'psoriasis pictures lichen planus and related diseases', 'nail fungus and other nail disease', 'exanthems and drug eruptions', 'hair loss photos alopecia and other hair diseases', 'systemic disease', 'vascular tumors', 'bullous disease photos')
PH2_CLASSNAMES = ('benign', 'malignant')
ISIC20_CLASSNAMES = ('benign', 'malignant')
HAM_2_CLASSNAMES = ("benign", "melanoma")
SNU_134_CLASSNAMES = ('epidermal cyst', 'paronychia', 'ota nevus', 'condyloma', 'keloid', 'alopecia areata', 'cellulitis', 'pyogenic granuloma', 'fifth disease', 'dermatofibroma', 'perioral dermatitis', 'squamous cell carcinoma', 'wart', 'riehl melanosis', 'urticaria pigmentosa', 'furuncle', 'bullous disease', 'herpes simplex', 'tinea faciale', 'lupus erythematosus', 'striae distensae', 'hemangioma', 'herpes zoster', 'malignant melanoma', 'pityriasis lichenoides et varioliformis acuta', 'pompholyx', 'nevus spilus', 'juvenile xanthogranuloma', 'actinic keratosis', 'nummular eczema', 'folliculitis', 'xerotic eczema', 'subungual hematoma', 'androgenic alopecia', 'prurigo nodularis', 'hand eczema', 'basal cell carcinoma', 'melanocytic nevus', 'lymphangioma', 'seborrheic keratosis', 'hypertrophic scar', 'idiopathic guttate hypomelanosis', 'keratoderma', 'erythema ab igne', 'lichen striatus', 'ingrowing nail', 'varicella', 'cafe au lait macule', 'poikiloderma', 'morphea', 'eczema herpeticum', 'milia', 'nail dystrophy', 'lichen nitidus', 'acanthosis nigricans', 'angular cheilitis', 'confluent and reticulated papillomatosis', 'syringoma', 'mucous cyst', 'becker nevus', 'tinea versicolor', 'psoriasis', 'port wine stain', 'neurofibromatosis', 'tinea cruris', 'xanthelasma', 'molluscum contagiosum', 'erythema annulare centrifugum', 'onychomycosis', 'scabies', 'neurofibroma', 'mucosal melanotic macule', 'rosacea', 'keratoacanthoma', 'angiofibroma', 'melanonychia', 'organoid nevus', 'nevus depigmentosus', 'epidermal nevus', 'tinea corporis', 'drug eruption', 'freckle', 'vitiligo', 'poroma', 'pityriasis alba', 'viral exanthem', 'blue nevus', 'acne', 'venous lake', 'atopic dermatitis', 'seborrheic dermatitis', 'lichen planus', 'exfoliative dermatitis', 'melasma', 'abscess', 'acute generalized exanthematous pustulosis', 'urticarial vasculitis', 'vasculitis', 'prurigo pigmentosa', 'impetigo', 'pityriasis lichenoides chronica', 'bowen disease', 'granuloma annulare', 'amyloidosis', 'urticaria', 'keratosis pilaris', 'livedo reticularis', 'steatocystoma multiplex', 'pityriasis rosea', 'mucocele', 'erythema multiforme', 'sebaceous hyperplasia', 'palmoplantar pustulosis', 'porokeratosis', 'lentigo', 'erythema nodosum', 'inflammed cyst', 'staphylococcal scalded skin syndrome', 'contact dermatitis', 'verruca plana', 'congenital nevus', 'lichen simplex chronicus', 'guttate psoriasis', 'angiokeratoma', 'tinea pedis', 'insect bite', 'pigmented progressive purpuric dermatosis', 'pyoderma gangrenosum', 'skin tag', 'lichen amyloidosis', 'abnormal', 'onycholysis', 'pustular psoriasis', 'telangiectasia')
SD_128_CLASSNAMES = ('acne keloidalis nuchae', 'acne vulgaris', 'actinic solar damage(actinic keratosis)', 'actinic solar damage(cutis rhomboidalis nuchae)', 'actinic solar damage(pigmentation)', 'actinic solar damage(solar elastosis)', 'actinic solar damage(solar purpura)', 'actinic solar damage(telangiectasia)', 'allergic contact dermatitis', 'alopecia areata', 'androgenetic alopecia', 'angioma', 'angular cheilitis', 'apocrine hydrocystoma', 'basal cell carcinoma', "beau's lines", 'benign keratosis', 'blue nevus', "bowen's disease", 'callus', 'candidiasis', 'cellulitis', 'clubbing of fingers', 'compound nevus', 'congenital nevus', "crowe's sign", 'cutaneous horn', 'darier-white disease', 'dermatofibroma', 'dermatosis papulosa nigra', 'desquamation', 'digital fibroma', 'dilated pore of winer', 'disseminated actinic porokeratosis', 'drug eruption', 'dry skin eczema', 'dyshidrosiform eczema', 'dysplastic nevus', 'eczema', 'epidermal nevus', 'epidermoid cyst', 'erythema craquele', 'erythema multiforme', 'exfoliative erythroderma', 'factitial dermatitis', 'favre racouchot', 'fibroma molle', 'fixed drug eruption', 'follicular mucinosis', 'granulation tissue', 'granuloma annulare', 'guttate psoriasis', 'halo nevus', 'herpes simplex virus', 'herpes zoster', 'hidradenitis suppurativa', 'hyperkeratosis palmaris et plantaris', 'hypertrichosis', 'ichthyosis', 'infantile atopic dermatitis', 'inverse psoriasis', 'junction nevus', 'keloid', 'keratoacanthoma', 'keratolysis exfoliativa of wende', 'keratosis pilaris', 'kerion', 'koilonychia', 'lentigo maligna melanoma', 'leukocytoclastic vasculitis', 'leukonychia', 'lichen planus', 'lichen sclerosis et atrophicus', 'lichen simplex chronicus', 'lipoma', 'livedo reticularis', 'lymphocytic infiltrate of jessner', 'malignant melanoma', 'median nail dystrophy', 'metastatic carcinoma', 'milia', 'myxoid cyst', 'nail dystrophy', 'nail psoriasis', 'neurodermatitis', 'neurofibroma', 'nevus incipiens', 'nevus sebaceous of jadassohn', 'nevus spilus', 'nummular eczema', 'onycholysis', 'onychomycosis', 'onychoschizia', 'paronychia', 'perioral dermatitis', 'pitted keratolysis', 'pityriasis rosea', 'pityrosporum folliculitis', 'pseudofolliculitis barbae', 'pseudorhinophyma', 'psoriasis', 'pustular psoriasis', 'pyogenic granuloma', 'radiodermatitis', 'rhinophyma', 'rosacea', 'scalp psoriasis', 'scar', 'sebaceous gland hyperplasia', 'seborrheic dermatitis', 'seborrheic keratosis', 'skin tag', 'stasis dermatitis', 'stasis edema', 'stasis ulcer', 'steroid acne', 'steroid use abusemisuse dermatitis', 'striae', 'syringoma', 'tinea corporis', 'tinea cruris', 'tinea faciale', 'tinea manus', 'tinea pedis', 'tinea versicolor', 'ulcer', 'verruca vulgaris', 'xerosis')
DAFFODIL_5_CLASSNAMES = ['vitiligo', 'acne', 'SJS/TEN', 'hyperpigmentation', 'nail psoriasis']

# Customized your own dataset
customized_CLASSNAMES = ['disease1', 'disease2', 'disease3']

OPENAI_SKIN_TEMPLATES = (
    lambda c: f'This is a skin image of {c}',
    lambda c: f'This is a skin image of {c}.',
    lambda c: f'A skin image of {c}.',
    lambda c: f'An image of {c}, a skin condition.',
    lambda c: f'{c}, a skin disorder, is shown in this image.',
    lambda c: f'The skin lesion depicted is {c}.',
    lambda c: f'The skin cancer in this image is {c}.',
    lambda c: f'This image depicts {c}, a type of skin cancer.',
)

OPENAI_IMAGENET_TEMPLATES = (
    lambda c: f'a bad photo of a {c}.',
    lambda c: f'a photo of many {c}.',
    lambda c: f'a sculpture of a {c}.',
    lambda c: f'a photo of the hard to see {c}.',
    lambda c: f'a low resolution photo of the {c}.',
    lambda c: f'a rendering of a {c}.',
    lambda c: f'graffiti of a {c}.',
    lambda c: f'a bad photo of the {c}.',
    lambda c: f'a cropped photo of the {c}.',
    lambda c: f'a tattoo of a {c}.',
    lambda c: f'the embroidered {c}.',
    lambda c: f'a photo of a hard to see {c}.',
    lambda c: f'a bright photo of a {c}.',
    lambda c: f'a photo of a clean {c}.',
    lambda c: f'a photo of a dirty {c}.',
    lambda c: f'a dark photo of the {c}.',
    lambda c: f'a drawing of a {c}.',
    lambda c: f'a photo of my {c}.',
    lambda c: f'the plastic {c}.',
    lambda c: f'a photo of the cool {c}.',
    lambda c: f'a close-up photo of a {c}.',
    lambda c: f'a black and white photo of the {c}.',
    lambda c: f'a painting of the {c}.',
    lambda c: f'a painting of a {c}.',
    lambda c: f'a pixelated photo of the {c}.',
    lambda c: f'a sculpture of the {c}.',
    lambda c: f'a bright photo of the {c}.',
    lambda c: f'a cropped photo of a {c}.',
    lambda c: f'a plastic {c}.',
    lambda c: f'a photo of the dirty {c}.',
    lambda c: f'a jpeg corrupted photo of a {c}.',
    lambda c: f'a blurry photo of the {c}.',
    lambda c: f'a photo of the {c}.',
    lambda c: f'a good photo of the {c}.',
    lambda c: f'a rendering of the {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'a photo of one {c}.',
    lambda c: f'a doodle of a {c}.',
    lambda c: f'a close-up photo of the {c}.',
    lambda c: f'a photo of a {c}.',
    lambda c: f'the origami {c}.',
    lambda c: f'the {c} in a video game.',
    lambda c: f'a sketch of a {c}.',
    lambda c: f'a doodle of the {c}.',
    lambda c: f'a origami {c}.',
    lambda c: f'a low resolution photo of a {c}.',
    lambda c: f'the toy {c}.',
    lambda c: f'a rendition of the {c}.',
    lambda c: f'a photo of the clean {c}.',
    lambda c: f'a photo of a large {c}.',
    lambda c: f'a rendition of a {c}.',
    lambda c: f'a photo of a nice {c}.',
    lambda c: f'a photo of a weird {c}.',
    lambda c: f'a blurry photo of a {c}.',
    lambda c: f'a cartoon {c}.',
    lambda c: f'art of a {c}.',
    lambda c: f'a sketch of the {c}.',
    lambda c: f'a embroidered {c}.',
    lambda c: f'a pixelated photo of a {c}.',
    lambda c: f'itap of the {c}.',
    lambda c: f'a jpeg corrupted photo of the {c}.',
    lambda c: f'a good photo of a {c}.',
    lambda c: f'a plushie {c}.',
    lambda c: f'a photo of the nice {c}.',
    lambda c: f'a photo of the small {c}.',
    lambda c: f'a photo of the weird {c}.',
    lambda c: f'the cartoon {c}.',
    lambda c: f'art of the {c}.',
    lambda c: f'a drawing of the {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a black and white photo of a {c}.',
    lambda c: f'the plushie {c}.',
    lambda c: f'a dark photo of a {c}.',
    lambda c: f'itap of a {c}.',
    lambda c: f'graffiti of the {c}.',
    lambda c: f'a toy {c}.',
    lambda c: f'itap of my {c}.',
    lambda c: f'a photo of a cool {c}.',
    lambda c: f'a photo of a small {c}.',
    lambda c: f'a tattoo of the {c}.',
)


# a much smaller subset of above prompts
# from https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb
SIMPLE_IMAGENET_TEMPLATES = (
    lambda c: f'itap of a {c}.',
    lambda c: f'a bad photo of the {c}.',
    lambda c: f'a origami {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'art of the {c}.',
    lambda c: f'a photo of the small {c}.',
)


IMAGENET_CLASSNAMES = (
    "tench", "goldfish", "great white shark", "tiger shark", "hammerhead shark", "electric ray",
    "stingray", "rooster", "hen", "ostrich", "brambling", "goldfinch", "house finch", "junco",
    "indigo bunting", "American robin", "bulbul", "jay", "magpie", "chickadee", "American dipper",
    "kite (bird of prey)", "bald eagle", "vulture", "great grey owl", "fire salamander",
    "smooth newt", "newt", "spotted salamander", "axolotl", "American bullfrog", "tree frog",
    "tailed frog", "loggerhead sea turtle", "leatherback sea turtle", "mud turtle", "terrapin",
    "box turtle", "banded gecko", "green iguana", "Carolina anole",
    "desert grassland whiptail lizard", "agama", "frilled-necked lizard", "alligator lizard",
    "Gila monster", "European green lizard", "chameleon", "Komodo dragon", "Nile crocodile",
    "American alligator", "triceratops", "worm snake", "ring-necked snake",
    "eastern hog-nosed snake", "smooth green snake", "kingsnake", "garter snake", "water snake",
    "vine snake", "night snake", "boa constrictor", "African rock python", "Indian cobra",
    "green mamba", "sea snake", "Saharan horned viper", "eastern diamondback rattlesnake",
    "sidewinder rattlesnake", "trilobite", "harvestman", "scorpion", "yellow garden spider",
    "barn spider", "European garden spider", "southern black widow", "tarantula", "wolf spider",
    "tick", "centipede", "black grouse", "ptarmigan", "ruffed grouse", "prairie grouse", "peafowl",
    "quail", "partridge", "african grey parrot", "macaw", "sulphur-crested cockatoo", "lorikeet",
    "coucal", "bee eater", "hornbill", "hummingbird", "jacamar", "toucan", "duck",
    "red-breasted merganser", "goose", "black swan", "tusker", "echidna", "platypus", "wallaby",
    "koala", "wombat", "jellyfish", "sea anemone", "brain coral", "flatworm", "nematode", "conch",
    "snail", "slug", "sea slug", "chiton", "chambered nautilus", "Dungeness crab", "rock crab",
    "fiddler crab", "red king crab", "American lobster", "spiny lobster", "crayfish", "hermit crab",
    "isopod", "white stork", "black stork", "spoonbill", "flamingo", "little blue heron",
    "great egret", "bittern bird", "crane bird", "limpkin", "common gallinule", "American coot",
    "bustard", "ruddy turnstone", "dunlin", "common redshank", "dowitcher", "oystercatcher",
    "pelican", "king penguin", "albatross", "grey whale", "killer whale", "dugong", "sea lion",
    "Chihuahua", "Japanese Chin", "Maltese", "Pekingese", "Shih Tzu", "King Charles Spaniel",
    "Papillon", "toy terrier", "Rhodesian Ridgeback", "Afghan Hound", "Basset Hound", "Beagle",
    "Bloodhound", "Bluetick Coonhound", "Black and Tan Coonhound", "Treeing Walker Coonhound",
    "English foxhound", "Redbone Coonhound", "borzoi", "Irish Wolfhound", "Italian Greyhound",
    "Whippet", "Ibizan Hound", "Norwegian Elkhound", "Otterhound", "Saluki", "Scottish Deerhound",
    "Weimaraner", "Staffordshire Bull Terrier", "American Staffordshire Terrier",
    "Bedlington Terrier", "Border Terrier", "Kerry Blue Terrier", "Irish Terrier",
    "Norfolk Terrier", "Norwich Terrier", "Yorkshire Terrier", "Wire Fox Terrier",
    "Lakeland Terrier", "Sealyham Terrier", "Airedale Terrier", "Cairn Terrier",
    "Australian Terrier", "Dandie Dinmont Terrier", "Boston Terrier", "Miniature Schnauzer",
    "Giant Schnauzer", "Standard Schnauzer", "Scottish Terrier", "Tibetan Terrier",
    "Australian Silky Terrier", "Soft-coated Wheaten Terrier", "West Highland White Terrier",
    "Lhasa Apso", "Flat-Coated Retriever", "Curly-coated Retriever", "Golden Retriever",
    "Labrador Retriever", "Chesapeake Bay Retriever", "German Shorthaired Pointer", "Vizsla",
    "English Setter", "Irish Setter", "Gordon Setter", "Brittany dog", "Clumber Spaniel",
    "English Springer Spaniel", "Welsh Springer Spaniel", "Cocker Spaniel", "Sussex Spaniel",
    "Irish Water Spaniel", "Kuvasz", "Schipperke", "Groenendael dog", "Malinois", "Briard",
    "Australian Kelpie", "Komondor", "Old English Sheepdog", "Shetland Sheepdog", "collie",
    "Border Collie", "Bouvier des Flandres dog", "Rottweiler", "German Shepherd Dog", "Dobermann",
    "Miniature Pinscher", "Greater Swiss Mountain Dog", "Bernese Mountain Dog",
    "Appenzeller Sennenhund", "Entlebucher Sennenhund", "Boxer", "Bullmastiff", "Tibetan Mastiff",
    "French Bulldog", "Great Dane", "St. Bernard", "husky", "Alaskan Malamute", "Siberian Husky",
    "Dalmatian", "Affenpinscher", "Basenji", "pug", "Leonberger", "Newfoundland dog",
    "Great Pyrenees dog", "Samoyed", "Pomeranian", "Chow Chow", "Keeshond", "brussels griffon",
    "Pembroke Welsh Corgi", "Cardigan Welsh Corgi", "Toy Poodle", "Miniature Poodle",
    "Standard Poodle", "Mexican hairless dog (xoloitzcuintli)", "grey wolf", "Alaskan tundra wolf",
    "red wolf or maned wolf", "coyote", "dingo", "dhole", "African wild dog", "hyena", "red fox",
    "kit fox", "Arctic fox", "grey fox", "tabby cat", "tiger cat", "Persian cat", "Siamese cat",
    "Egyptian Mau", "cougar", "lynx", "leopard", "snow leopard", "jaguar", "lion", "tiger",
    "cheetah", "brown bear", "American black bear", "polar bear", "sloth bear", "mongoose",
    "meerkat", "tiger beetle", "ladybug", "ground beetle", "longhorn beetle", "leaf beetle",
    "dung beetle", "rhinoceros beetle", "weevil", "fly", "bee", "ant", "grasshopper",
    "cricket insect", "stick insect", "cockroach", "praying mantis", "cicada", "leafhopper",
    "lacewing", "dragonfly", "damselfly", "red admiral butterfly", "ringlet butterfly",
    "monarch butterfly", "small white butterfly", "sulphur butterfly", "gossamer-winged butterfly",
    "starfish", "sea urchin", "sea cucumber", "cottontail rabbit", "hare", "Angora rabbit",
    "hamster", "porcupine", "fox squirrel", "marmot", "beaver", "guinea pig", "common sorrel horse",
    "zebra", "pig", "wild boar", "warthog", "hippopotamus", "ox", "water buffalo", "bison",
    "ram (adult male sheep)", "bighorn sheep", "Alpine ibex", "hartebeest", "impala (antelope)",
    "gazelle", "arabian camel", "llama", "weasel", "mink", "European polecat",
    "black-footed ferret", "otter", "skunk", "badger", "armadillo", "three-toed sloth", "orangutan",
    "gorilla", "chimpanzee", "gibbon", "siamang", "guenon", "patas monkey", "baboon", "macaque",
    "langur", "black-and-white colobus", "proboscis monkey", "marmoset", "white-headed capuchin",
    "howler monkey", "titi monkey", "Geoffroy's spider monkey", "common squirrel monkey",
    "ring-tailed lemur", "indri", "Asian elephant", "African bush elephant", "red panda",
    "giant panda", "snoek fish", "eel", "silver salmon", "rock beauty fish", "clownfish",
    "sturgeon", "gar fish", "lionfish", "pufferfish", "abacus", "abaya", "academic gown",
    "accordion", "acoustic guitar", "aircraft carrier", "airliner", "airship", "altar", "ambulance",
    "amphibious vehicle", "analog clock", "apiary", "apron", "trash can", "assault rifle",
    "backpack", "bakery", "balance beam", "balloon", "ballpoint pen", "Band-Aid", "banjo",
    "baluster / handrail", "barbell", "barber chair", "barbershop", "barn", "barometer", "barrel",
    "wheelbarrow", "baseball", "basketball", "bassinet", "bassoon", "swimming cap", "bath towel",
    "bathtub", "station wagon", "lighthouse", "beaker", "military hat (bearskin or shako)",
    "beer bottle", "beer glass", "bell tower", "baby bib", "tandem bicycle", "bikini",
    "ring binder", "binoculars", "birdhouse", "boathouse", "bobsleigh", "bolo tie", "poke bonnet",
    "bookcase", "bookstore", "bottle cap", "hunting bow", "bow tie", "brass memorial plaque", "bra",
    "breakwater", "breastplate", "broom", "bucket", "buckle", "bulletproof vest",
    "high-speed train", "butcher shop", "taxicab", "cauldron", "candle", "cannon", "canoe",
    "can opener", "cardigan", "car mirror", "carousel", "tool kit", "cardboard box / carton",
    "car wheel", "automated teller machine", "cassette", "cassette player", "castle", "catamaran",
    "CD player", "cello", "mobile phone", "chain", "chain-link fence", "chain mail", "chainsaw",
    "storage chest", "chiffonier", "bell or wind chime", "china cabinet", "Christmas stocking",
    "church", "movie theater", "cleaver", "cliff dwelling", "cloak", "clogs", "cocktail shaker",
    "coffee mug", "coffeemaker", "spiral or coil", "combination lock", "computer keyboard",
    "candy store", "container ship", "convertible", "corkscrew", "cornet", "cowboy boot",
    "cowboy hat", "cradle", "construction crane", "crash helmet", "crate", "infant bed",
    "Crock Pot", "croquet ball", "crutch", "cuirass", "dam", "desk", "desktop computer",
    "rotary dial telephone", "diaper", "digital clock", "digital watch", "dining table",
    "dishcloth", "dishwasher", "disc brake", "dock", "dog sled", "dome", "doormat", "drilling rig",
    "drum", "drumstick", "dumbbell", "Dutch oven", "electric fan", "electric guitar",
    "electric locomotive", "entertainment center", "envelope", "espresso machine", "face powder",
    "feather boa", "filing cabinet", "fireboat", "fire truck", "fire screen", "flagpole", "flute",
    "folding chair", "football helmet", "forklift", "fountain", "fountain pen", "four-poster bed",
    "freight car", "French horn", "frying pan", "fur coat", "garbage truck",
    "gas mask or respirator", "gas pump", "goblet", "go-kart", "golf ball", "golf cart", "gondola",
    "gong", "gown", "grand piano", "greenhouse", "radiator grille", "grocery store", "guillotine",
    "hair clip", "hair spray", "half-track", "hammer", "hamper", "hair dryer", "hand-held computer",
    "handkerchief", "hard disk drive", "harmonica", "harp", "combine harvester", "hatchet",
    "holster", "home theater", "honeycomb", "hook", "hoop skirt", "gymnastic horizontal bar",
    "horse-drawn vehicle", "hourglass", "iPod", "clothes iron", "carved pumpkin", "jeans", "jeep",
    "T-shirt", "jigsaw puzzle", "rickshaw", "joystick", "kimono", "knee pad", "knot", "lab coat",
    "ladle", "lampshade", "laptop computer", "lawn mower", "lens cap", "letter opener", "library",
    "lifeboat", "lighter", "limousine", "ocean liner", "lipstick", "slip-on shoe", "lotion",
    "music speaker", "loupe magnifying glass", "sawmill", "magnetic compass", "messenger bag",
    "mailbox", "tights", "one-piece bathing suit", "manhole cover", "maraca", "marimba", "mask",
    "matchstick", "maypole", "maze", "measuring cup", "medicine cabinet", "megalith", "microphone",
    "microwave oven", "military uniform", "milk can", "minibus", "miniskirt", "minivan", "missile",
    "mitten", "mixing bowl", "mobile home", "ford model t", "modem", "monastery", "monitor",
    "moped", "mortar and pestle", "graduation cap", "mosque", "mosquito net", "vespa",
    "mountain bike", "tent", "computer mouse", "mousetrap", "moving van", "muzzle", "metal nail",
    "neck brace", "necklace", "baby pacifier", "notebook computer", "obelisk", "oboe", "ocarina",
    "odometer", "oil filter", "pipe organ", "oscilloscope", "overskirt", "bullock cart",
    "oxygen mask", "product packet / packaging", "paddle", "paddle wheel", "padlock", "paintbrush",
    "pajamas", "palace", "pan flute", "paper towel", "parachute", "parallel bars", "park bench",
    "parking meter", "railroad car", "patio", "payphone", "pedestal", "pencil case",
    "pencil sharpener", "perfume", "Petri dish", "photocopier", "plectrum", "Pickelhaube",
    "picket fence", "pickup truck", "pier", "piggy bank", "pill bottle", "pillow", "ping-pong ball",
    "pinwheel", "pirate ship", "drink pitcher", "block plane", "planetarium", "plastic bag",
    "plate rack", "farm plow", "plunger", "Polaroid camera", "pole", "police van", "poncho",
    "pool table", "soda bottle", "plant pot", "potter's wheel", "power drill", "prayer rug",
    "printer", "prison", "missile", "projector", "hockey puck", "punching bag", "purse", "quill",
    "quilt", "race car", "racket", "radiator", "radio", "radio telescope", "rain barrel",
    "recreational vehicle", "fishing casting reel", "reflex camera", "refrigerator",
    "remote control", "restaurant", "revolver", "rifle", "rocking chair", "rotisserie", "eraser",
    "rugby ball", "ruler measuring stick", "sneaker", "safe", "safety pin", "salt shaker", "sandal",
    "sarong", "saxophone", "scabbard", "weighing scale", "school bus", "schooner", "scoreboard",
    "CRT monitor", "screw", "screwdriver", "seat belt", "sewing machine", "shield", "shoe store",
    "shoji screen / room divider", "shopping basket", "shopping cart", "shovel", "shower cap",
    "shower curtain", "ski", "balaclava ski mask", "sleeping bag", "slide rule", "sliding door",
    "slot machine", "snorkel", "snowmobile", "snowplow", "soap dispenser", "soccer ball", "sock",
    "solar thermal collector", "sombrero", "soup bowl", "keyboard space bar", "space heater",
    "space shuttle", "spatula", "motorboat", "spider web", "spindle", "sports car", "spotlight",
    "stage", "steam locomotive", "through arch bridge", "steel drum", "stethoscope", "scarf",
    "stone wall", "stopwatch", "stove", "strainer", "tram", "stretcher", "couch", "stupa",
    "submarine", "suit", "sundial", "sunglasses", "sunglasses", "sunscreen", "suspension bridge",
    "mop", "sweatshirt", "swim trunks / shorts", "swing", "electrical switch", "syringe",
    "table lamp", "tank", "tape player", "teapot", "teddy bear", "television", "tennis ball",
    "thatched roof", "front curtain", "thimble", "threshing machine", "throne", "tile roof",
    "toaster", "tobacco shop", "toilet seat", "torch", "totem pole", "tow truck", "toy store",
    "tractor", "semi-trailer truck", "tray", "trench coat", "tricycle", "trimaran", "tripod",
    "triumphal arch", "trolleybus", "trombone", "hot tub", "turnstile", "typewriter keyboard",
    "umbrella", "unicycle", "upright piano", "vacuum cleaner", "vase", "vaulted or arched ceiling",
    "velvet fabric", "vending machine", "vestment", "viaduct", "violin", "volleyball",
    "waffle iron", "wall clock", "wallet", "wardrobe", "military aircraft", "sink",
    "washing machine", "water bottle", "water jug", "water tower", "whiskey jug", "whistle",
    "hair wig", "window screen", "window shade", "Windsor tie", "wine bottle", "airplane wing",
    "wok", "wooden spoon", "wool", "split-rail fence", "shipwreck", "sailboat", "yurt", "website",
    "comic book", "crossword", "traffic or street sign", "traffic light", "dust jacket", "menu",
    "plate", "guacamole", "consomme", "hot pot", "trifle", "ice cream", "popsicle", "baguette",
    "bagel", "pretzel", "cheeseburger", "hot dog", "mashed potatoes", "cabbage", "broccoli",
    "cauliflower", "zucchini", "spaghetti squash", "acorn squash", "butternut squash", "cucumber",
    "artichoke", "bell pepper", "cardoon", "mushroom", "Granny Smith apple", "strawberry", "orange",
    "lemon", "fig", "pineapple", "banana", "jackfruit", "cherimoya (custard apple)", "pomegranate",
    "hay", "carbonara", "chocolate syrup", "dough", "meatloaf", "pizza", "pot pie", "burrito",
    "red wine", "espresso", "tea cup", "eggnog", "mountain", "bubble", "cliff", "coral reef",
    "geyser", "lakeshore", "promontory", "sandbar", "beach", "valley", "volcano", "baseball player",
    "bridegroom", "scuba diver", "rapeseed", "daisy", "yellow lady's slipper", "corn", "acorn",
    "rose hip", "horse chestnut seed", "coral fungus", "agaric", "gyromitra", "stinkhorn mushroom",
    "earth star fungus", "hen of the woods mushroom", "bolete", "corn cob", "toilet paper"
)

